Packaging
SUSE-Enceladus/azuremetadata pull request #4
Opened 2020-02-21 16:18 UTC by ikapelyukhin

In this PR:
* Packaging

I've set the version to `5.0.0` (previous Perl version has `4.0.1`), the package name now however is `python3-azuremetadata`, rather than `azuremetadata`.

* What should the version number be? (`5.0.0` or `1.0.0`)
* Do we need an ECO to obsolete `azuremetadata`?

Coming up next:

- Getting actual metadata with HTTP client
- Disk tag (if we actually need it)
- Man page

2020-02-21 16:25 UTC, ikapelyukhin commented
Package is build in [IBS](https://build.suse.de/package/show/home:ikapelyukhin/python3-azuremetadata) (it's building, but the fixtures aren't packaged).

2020-02-21 23:06 UTC, rjschwei requested changes

2020-02-21 23:06 UTC, rjschwei commented on python3-azuremetadata.spec
> +Obsoletes:      azuremetadata
Needs a version, i.e. "Obsoletes: azuremetata < 5.0.0" also needs "Provides: azuremetadata" , i.e. the regular package split/rename setup

2020-02-21 23:06 UTC, rjschwei commented on setup.py
> +#!/usr/bin/env python
that should be pointing to python3

2020-02-21 23:06 UTC, rjschwei commented on Makefile
> +	python setup.py install --prefix="$(PREFIX)" --root="$(DESTDIR)"
python3

2020-02-22 01:04 UTC, ikapelyukhin commented on python3-azuremetadata.spec
> +Obsoletes:      azuremetadata
@rjschwei are we calling the package `azuremetadata` or `python3-azuremetadata`?

2020-02-22 01:28 UTC, rjschwei commented on python3-azuremetadata.spec
> +Obsoletes:      azuremetadata
We will call it python3-azuremetadata as it is split into a command line processor and a library implementation that someone else could use to write their own cli or directly in some other code.

2020-02-24 13:29 UTC, ikapelyukhin commented on setup.py
> +#!/usr/bin/env python
OK, fixed. I've pointed everything (inclunding `azuremetadata`) explicitly to `/usr/bin/python3`, because rpmlint complains about `/usr/bin/env`.

2020-02-24 13:29 UTC, ikapelyukhin commented on Makefile
> +	python setup.py install --prefix="$(PREFIX)" --root="$(DESTDIR)"
Fixed.

2020-02-24 13:29 UTC, ikapelyukhin commented on python3-azuremetadata.spec
> +Obsoletes:      azuremetadata
Fixed.

2020-02-24 13:35 UTC, rjschwei approved these changes

2020-02-25 11:10 UTC, merged